### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'items')

### ISSUE THREAD

**Issue by Minuit-Ferina** [Minuit-Ferina/vscode-lsl#5]
```
2023-05-21 14:09:36.282 [error] [MinuitFerina.lsl-tools] provider FAILED
2023-05-21 14:09:36.284 [error] TypeError: Cannot read properties of undefined (reading 'items')
	at Vc (c:\Users\minuitferina\.vscode\extensions\minuitferina.lsl-tools-0.1.0-beta1\client\out\extension.js:1064:2123)
	at Vc (c:\Users\minuitferina\.vscode\extensions\minuitferina.lsl-tools-0.1.0-beta1\client\out\extension.js:1064:2198)
	at Yc (c:\Users\minuitferina\.vscode\extensions\minuitferina.lsl-tools-0.1.0-beta1\client\out\extension.js:1064:1971)
	at Object.<anonymous> (c:\Users\minuitferina\.vscode\extensions\minuitferina.lsl-tools-0.1.0-beta1\client\out\extension.js:1064:3543)
	at Generator.next (<anonymous>)
	at c:\Users\minuitferina\.vscode\extensions\minuitferina.lsl-tools-0.1.0-beta1\client\out\extension.js:1:895
	at new Promise (<anonymous>)
	at at (c:\Users\minuitferina\.vscode\extensions\minuitferina.lsl-tools-0.1.0-beta1\client\out\extension.js:1:715)
	at Object.provideCompletionItems (c:\Users\minuitferina\.vscode\extensions\minuitferina.lsl-tools-0.1.0-beta1\client\out\extension.js:1064:3511)
	at oe.provideCompletionItems (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:52903)
	at c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:73510
	at le.s (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:65165)
	at le.$provideCompletionItems (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:73496)
	at a.N (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:110:11620)
	at a.M (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:110:11338)
	at a.H (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:110:10393)
	at a.G (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:110:9412)
	at c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:110:8200
	at v.invoke (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at h.deliver (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
	at i.fire (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
	at g.fire (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14852)
	at c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:32403
	at v.invoke (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:145)
	at h.deliver (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:2121)
	at i.fire (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:63:1729)
	at g.fire (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:72:14852)
	at MessagePortMain.<anonymous> (c:\Users\minuitferina\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:30529)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

**Comment by Minuit-Ferina** [comment]
fixed there 73d1b61e1df90d44621103887896c1b53b813287
